mpu9250driver_node:
  ros__parameters:
    calibrate: True
    gyro_range: 0
    accel_range: 0
    dlpf_bandwidth: 2
    gyro_x_offset: 0.0 # [deg/s]
    gyro_y_offset: 0.0 # [deg/s]
    gyro_z_offset: 0.0 # [deg/s]
    accel_x_offset: 0.0 # [m/s^2]
    accel_y_offset: 0.0 # [m/s^2]
    accel_z_offset: 0.0 # [m/s^2]
    frequency: 50 # [Hz]
